// This file is automatically generated by scripts/update_mentors.mjs
// Do not edit this file manually.

export const mentors = [
  {
    "name": "みるく",
    "leaders": "15期",
    "course": "DTM",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "図工室の先生が優しかったから、昼休みずっと遊んでた"
  },
  {
    "name": "すしろー",
    "leaders": "17期",
    "course": "DTM",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "学芸発表会、年ごとに出し物の内容が劇→合奏→図工作品→劇→…って感じでローテしてて楽しかったなぁ"
  },
  {
    "name": "きぺお",
    "leaders": "15期",
    "course": "映像制作",
    "region": "東海🥠",
    "license": "勝者",
    "summerMemory": "ポケットモンスターブラック・ホワイト"
  },
  {
    "name": "はるちろ",
    "leaders": "15期",
    "course": "Minecraft",
    "region": "東海🥠",
    "license": "勝者",
    "summerMemory": "秘密基地で木の貿易をしてた"
  },
  {
    "name": "ニュイ",
    "leaders": "17期",
    "course": "アニメーション",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "自転車に乗れるようになる前に一輪車に乗れるようになった"
  },
  {
    "name": "ゆちゃ",
    "leaders": "17期",
    "course": "映像制作",
    "region": "関東🏮",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "小学校がいちばんの黒歴史"
  },
  {
    "name": "アンビ",
    "leaders": "16期",
    "course": "Unity",
    "region": "関西🧆",
    "license": "勝者",
    "summerMemory": "バスケ漬けの毎日！"
  },
  {
    "name": "ひらけー！",
    "leaders": "17期",
    "course": "iPhone",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "スキー合宿でお尻で滑った！！"
  },
  {
    "name": "ほなみん",
    "leaders": "17期",
    "course": "映像制作",
    "region": "関西🧆",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "引っ越し🏠🏠"
  },
  {
    "name": "ゆるゆる",
    "leaders": "12期",
    "course": "Minecraft",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "校庭で野生の犬にめちゃめちゃ追い回された。"
  },
  {
    "name": "やまゆ",
    "leaders": "17期",
    "course": "Unity",
    "region": "関西🧆",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "友達みんなで集まってクリスマスケーキ手作りした"
  },
  {
    "name": "ひかぴ",
    "leaders": "16期",
    "course": "アニメーション",
    "region": "関東🏮",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "読書感想文で、映画化してた本の映画の方を観た感想書いてゴリ押したら、代表に選ばれちゃったこと📚"
  },
  {
    "name": "あいりす",
    "leaders": "14期",
    "course": "メディアアート",
    "region": "関東🏮",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "覚えてないし〜！うーん、リレー選"
  },
  {
    "name": "きほもり",
    "leaders": "12期",
    "course": "iPhone",
    "region": "関東🏮",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "小6の大縄大会が嫌すぎて、当日休みたいなーと思ってたら、本当熱が出て欠席することになった🙌快復後にルンルンで学校行ったら、担任が「自分たちのクラスは優勝したが、きほが休んでいたから意味がない！」っていって、学活の時間に私のクラスだけもう一回記録更新をかけて大縄することになった。いい先生ではあったけど、ここに関しては要らない熱意だった。"
  },
  {
    "name": "ようる",
    "leaders": "16期",
    "course": "Unity",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "妖怪ウォッチ真打のバスターズ一生やってた🐈"
  },
  {
    "name": "きょーりゅー",
    "leaders": "13期",
    "course": "iPhone",
    "region": "関東🏮",
    "license": "勝者",
    "summerMemory": "思いつかなすぎる、"
  },
  {
    "name": "りじ",
    "leaders": "13期",
    "course": "映像制作",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "好きだった女の子の家にあった少女漫画を見てその日は眠れなかった。"
  },
  {
    "name": "ばんしぃ",
    "leaders": "17期",
    "course": "アニメーション",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "防災宿泊体験の時に夜先生に屋上に連れて行ってもらって星空見せてくれた事"
  },
  {
    "name": "まぽこ",
    "leaders": "17期",
    "course": "iPhone",
    "region": "関西🧆",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "運動会の組体操！！！"
  },
  {
    "name": "chanまい",
    "leaders": "16期",
    "course": "映像制作",
    "region": "関東🏮",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "ソーラン節がち勢の学校で、先生が北海道まで行って学んだガチのよさこいソーランを運動会で踊ってたこと"
  },
  {
    "name": "ほのぴ",
    "leaders": "16期",
    "course": "iPhone",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "逆上がりしたら歯が抜けたこと🦷"
  },
  {
    "name": "まさぴ〜",
    "leaders": "17期",
    "course": "Minecraft",
    "region": "関東🏮",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "ベル使ってみんなと音楽コンクール出た！"
  },
  {
    "name": "あづき",
    "leaders": "13期",
    "course": "映像制作",
    "region": "関東🏮",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "じゃんけん列車学年優勝したこと"
  },
  {
    "name": "ばく",
    "leaders": "16期",
    "course": "Webデザイン",
    "region": "関西🧆",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "友達と一緒に学校内のありとあらゆる場所散策して秘密基地10個以上作ってた"
  },
  {
    "name": "はたこー",
    "leaders": "16期",
    "course": "Minecraft",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "朝から晩まで公園で遊んだこと"
  },
  {
    "name": "もーりー",
    "leaders": "16期",
    "course": "映像制作",
    "region": "関西🧆",
    "license": "勝者",
    "summerMemory": "給食でくじらの唐揚げが出たこと"
  },
  {
    "name": "あおぽん",
    "leaders": "17期",
    "course": "iPhone",
    "region": "関西🧆",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "修学旅行！"
  },
  {
    "name": "さとたい",
    "leaders": "17期",
    "course": "Unity",
    "region": "その他",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "よさこいソーラン祭り"
  },
  {
    "name": "たーとる",
    "leaders": "17期",
    "course": "Unity",
    "region": "関東🏮",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "自分の傘につまずいたことが何回もあります"
  },
  {
    "name": "まんじ",
    "leaders": "17期",
    "course": "DTM",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "オーストラリアでカンガルーとツーショ撮ったこと"
  },
  {
    "name": "こーた",
    "leaders": "16期",
    "course": "映像制作",
    "region": "山梨🍇",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "掃除の時のバケツが腐った牛乳の匂いでした"
  },
  {
    "name": "きゃあ。",
    "leaders": "6期",
    "course": "映像制作",
    "region": "関東🏮",
    "license": "勝者",
    "summerMemory": "ボール式マウスのボール集めてました"
  },
  {
    "name": "ネンネン",
    "leaders": "15期",
    "course": "アニメーション",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "図書室の本を9割読み切ったこと"
  },
  {
    "name": "ねお",
    "leaders": "15期",
    "course": "アニメーション",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "ちいちゃんのかげおくりのちいちゃんやった"
  },
  {
    "name": "まっすー",
    "leaders": "16期",
    "course": "映像制作",
    "region": "東海🥠",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "応援団長した！！"
  },
  {
    "name": "わたみ",
    "leaders": "15期",
    "course": "Webデザイン",
    "region": "関東🏮",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "小6の夏、塾の夏季講習の前後で毎日マクドに4,5時間友達と入り浸ってたこと🍟🍔"
  },
  {
    "name": "ゴゴティー",
    "leaders": "17期",
    "course": "Unity",
    "region": "東海🥠",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "修学旅行！！"
  },
  {
    "name": "しろ",
    "leaders": "16期",
    "course": "アニメーション",
    "region": "関東🏮",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "50周年の記念に航空写真撮った！"
  },
  {
    "name": "あるが",
    "leaders": "13期",
    "course": "Unity",
    "region": "関東🏮",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "トルコに旅行に行ったこと！"
  },
  {
    "name": "キノヤ",
    "leaders": "15期",
    "course": "Minecraft",
    "region": "関東🏮",
    "license": "勝者",
    "summerMemory": "遠い昔すぎて覚えてない😭"
  },
  {
    "name": "りっちゃん",
    "leaders": "16期",
    "course": "Webデザイン",
    "region": "関西🧆",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "友達とトカゲ捕まえて筆箱で飼育？してたこと！"
  },
  {
    "name": "ほしょ",
    "leaders": "12期",
    "course": "iPhone",
    "region": "関西🧆",
    "license": "勝者",
    "summerMemory": "サッカーするために朝5時に起きて登校してた"
  },
  {
    "name": "きゃんた",
    "leaders": "16期",
    "course": "映像制作",
    "region": "関西🧆",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "ねりけし"
  },
  {
    "name": "KURO",
    "leaders": "13期",
    "course": "映像制作",
    "region": "関西🧆",
    "license": "勝者",
    "summerMemory": "友達の靴を雪が詰まった噴水の中にぶち込んだら、校長先生が見つけて呼び出されたこと"
  },
  {
    "name": "もりね",
    "leaders": "11期",
    "course": "Webデザイン",
    "region": "関東🏮",
    "license": "勝者",
    "summerMemory": "塾の帰り道、行き場のないストレスを紛らわせるために、歩道橋の上から眼下の車に向けてエアガンを撃っていた。"
  },
  {
    "name": "ヨヨギ",
    "leaders": "16期",
    "course": "Unity",
    "region": "関東🏮",
    "license": "勝者だが敗者（ペーパー）",
    "summerMemory": "修学旅行で江ノ島泊まった！"
  },
  {
    "name": "ゆわ",
    "leaders": "16期",
    "course": "アニメーション",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "5月に長野にキャンプをしに行きました。キャンプでは、ナイトウォークをしたり、おにぎりを食べたりしました。ナイトウォークをしていたとちゅうに、一回地面にねて、星座を見ました。星座は2~4つありました。そこで、わたしのぼうえんきょうのカバーで、お月さまを見たら、花火に見えました。そのつぎのことをおしえます。そして、帰ったら、たくさんの人が、「先生、足がいたい。」と言っていました。そして、ねぶくろでねて、つぎの日におきて、ごはんを食べました。それからみんなが、楽しくあそんでいるあいだに、ゆりとさきがとげがささったと、言っていました。わたしは、さむいさむいと、ひなたぼっこをしてみたり、はしりまわったりしてみましたが、ちっともあたたかくかりません。そのとき、先生が、｢ゆうあ、ねつはかってみよう。｣と、話しかけてきました。ねつをはかったら、39.2どぐらいでした。そして、帰りに、わたしはおにぎりを買って食べました。バスで、わたしがねつをだしたので、先生が横にすわってくれました。おやつの時間には、ふつうにおやつをこうかんしたりして、たのしくおやつを食べていたので、先生は「しょくよくあってよかった。」と、つぶやいていました。わたしのよこにすわっていたさきも、「よかった。」という顔をしていました。自分でも、だいじょうぶだなと思いました。 ナイトウォークの前にあったことはなんこかありました。キャンプに行くときは、2~4人が学校から見おくってくれました。わたしは、すごくうれしくなって、わくわくして行きました。とちゅうで、バスの中でフルーツブレークや、お休みがありました。最初のお休みは、トイレに行くだけでした2番目のお休みは、昼ごはんやあそび、しゃしんをとるなど、いろいろなことをしました。公園にはタイヤのはしごや、タイヤのぶらんこみたいなもの、それからへいきんだいであそびました。木でできていたへいきんだいだったので、足にとげがささってしまいました。それで、きがえました。そのふくはちくちくしていなかったので、木にすわっていたズボンに木のとげがささっていたのです。きがえたとたん「ふーっ」と、ためいきをついてしまいました。わたしは、今この前のことを思うと、「あの時はさきとゆりとお友だち、それよりも同じ色のお友だちだったんだなー」と思います。本当にそうだったのかはわかりません。でも、すっごく楽しかったことは、本当に心にはのこっています。では、どうやってねつになったかというと、さいしょ、みんなでおふろそうじをしていました。何人かが水であそんでいました。その人たちはおこられて、のこっていたのがわたしとゆきの。「かべをそうじしてからゆかをそうじして。」と、先生の言うとおりにしました。終わってから、ゆきののズボンとわたしのズボンはびしょぬれでした。なので日にあたるところで、ズボンをかわかしていました。そのかわかしていたズボンをはいていたときに熱が出る元になったのです。ズボンをぬいですくに、走れば、たぶんねつにならなかったのでしょうそれはそうなのかはわかりません。帰るときに、もっといたかったよーと思う人もいたでしょうね。 わるいこともありましたがすっごくたのしかったです。またらいねんもたのしみにしています。"
  },
  {
    "name": "うらっしゅ",
    "leaders": "15期",
    "course": "Minecraft",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "初恋の人とリフトが隣になった！"
  },
  {
    "name": "きゅる",
    "leaders": "15期",
    "course": "映像制作",
    "region": "関東🏮",
    "license": "敗者！助手席は任せてください",
    "summerMemory": "運動会の組体操で、ピラミッドの1番上やったこと！！"
  },
  {
    "name": "zenzen",
    "leaders": "16期",
    "course": "Minecraft",
    "region": "関東🏮",
    "license": "勝者",
    "summerMemory": "学校の帰りの会でみんなでBack to the futureをちびちび見たことですかね。一年かけて3の途中まで見れました"
  }
];
