import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, '..');
const csvPath = path.join(rootDir, 'Flashami-20260216-0218-Flacation2026-form.csv');
const outputPath = path.join(rootDir, 'handlers', 'mentors_data.mjs');

// Simple CSV Parser handling quoted fields
function parseCSV(text) {
    const lines = text.split(/\r?\n/).filter(line => line.trim() !== '');
    const headers = lines[0].split(',').map(h => h.trim());
    const result = [];

    for (let i = 1; i < lines.length; i++) {
        const line = lines[i];
        const row = [];
        let inQuotes = false;
        let currentValue = '';

        for (let j = 0; j < line.length; j++) {
            const char = line[j];
            if (char === '"') {
                inQuotes = !inQuotes;
            } else if (char === ',' && !inQuotes) {
                row.push(currentValue.trim());
                currentValue = '';
            } else {
                currentValue += char;
            }
        }
        row.push(currentValue.trim()); // Push the last value

        if (row.length === headers.length) {
            const obj = {};
            headers.forEach((header, index) => {
                obj[header] = row[index].replace(/^"|"$/g, ''); // Remove surrounding quotes if present
            });
            result.push(obj);
        }
    }
    return result;
}

try {
    const csvContent = fs.readFileSync(csvPath, 'utf-8');
    const records = parseCSV(csvContent);

    const mentors = records.map(record => ({
        name: record['name'],
        leaders: record['Leaders期🕶️'],
        course: record['course'],
        region: record['region'],
        license: record['免許🚘'],
        summerMemory: record['memories']
    }));

    const fileContent = `// This file is automatically generated by scripts/update_mentors.mjs
// Do not edit this file manually.

export const mentors = ${JSON.stringify(mentors, null, 2)};
`;

    fs.writeFileSync(outputPath, fileContent);
    console.log(`Successfully updated mentors data at ${outputPath}`);
    console.log(`Total mentors: ${mentors.length}`);

} catch (error) {
    console.error('Error updating mentors:', error);
    process.exit(1);
}
